services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: relay-postgres
    environment:
      POSTGRES_DB: relay_db
      POSTGRES_USER: relay_user
      POSTGRES_PASSWORD: relay_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U relay_user -d relay_db"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - relay-network

  # Go Relay Server
  go-relay:
    build:
      context: ./go-relay
      dockerfile: Dockerfile
    container_name: relay-server
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=relay_db
      - DB_USER=relay_user
      - DB_PASSWORD=relay_password
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - relay-network

  # Web Client
  web-client:
    build:
      context: ./web-client
      dockerfile: Dockerfile
    container_name: relay-web-client
    ports:
      - "3001:80"
    depends_on:
      - go-relay
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:80/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - relay-network

  # PC App
  pc-app:
    build:
      context: ./pc-app
      dockerfile: Dockerfile
    container_name: relay-pc-app
    ports:
      - "3002:80"
    depends_on:
      - go-relay
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:80/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - relay-network

volumes:
  postgres_data:

networks:
  relay-network:
    driver: bridge
