version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: relay-postgres-dev
    environment:
      POSTGRES_DB: relay_db
      POSTGRES_USER: relay_user
      POSTGRES_PASSWORD: relay_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U relay_user -d relay_db"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - relay-network

  # Go Relay Server (Development)
  go-relay:
    build:
      context: ./go-relay
      dockerfile: Dockerfile.dev
    container_name: relay-server-dev
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=relay_db
      - DB_USER=relay_user
      - DB_PASSWORD=relay_password
    volumes:
      - ./go-relay:/app
      - go_cache:/go
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    command: go run ./cmd/server
    networks:
      - relay-network

  # Web Client (Development)
  web-client:
    build:
      context: ./web-client
      dockerfile: Dockerfile.dev
    container_name: relay-web-client-dev
    volumes:
      - ./web-client:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - go-relay
    command: npm start
    networks:
      - relay-network

  # PC App (Development)
  pc-app:
    build:
      context: ./pc-app
      dockerfile: Dockerfile.dev
    container_name: relay-pc-app-dev
    volumes:
      - ./pc-app:/app
      - /app/node_modules
    ports:
      - "3002:3002"
    depends_on:
      - go-relay
    command: npm run dev
    networks:
      - relay-network

volumes:
  postgres_data:
  go_cache:

networks:
  relay-network:
    driver: bridge
